### ISSUE TITLE
Interval expression produces error

### ISSUE THREAD

**Issue by tasso94** [nikku/feel-playground#1]
When I enter `[(key_figures.avg_score*.8)..key_figures.avg_score]` an error is shown in the Tree.

**Comment by nikku** [comment]
Yes, because that is not a valid feel expression.

Components in intervals must be endpoints => simple literals. `[EXPRESSION...EXPRESSION]` is not a valid feel expression. 

The parser attempts best efford and tries to parse your expression as a list.

**Comment by nikku** [comment]
By the way, you can also deep link your expression / editor contents, cf. [`[a..b]`](https://nikku.github.io/feel-playground/#%5B(key_figures.avg_score*.8)..key_figures.avg_score%5D;%7B%0A%20%20%22vegetables%22%3A%20%5B%20%22garlic%22%2C%20%22tomato%22%20%5D%2C%0A%20%20%22Mike's%20age%22%3A%2035%0A%7D;true;expression)

**Comment by nikku** [comment]
Quoting from the spec (`10.3.1.2 Grammar rules`):

```
8. interval = ( open interval start | closed interval start ) , endpoint , ".." , endpoint , ( open interval end | closed interval
end ) ;
16. endpoint = simple value ;
17. simple value = qualified name | simple literal ;
```
