### ISSUE TITLE
matches() function is not supported

### ISSUE THREAD

**Issue by mschoe** [nikku/feel-playground#16]
### Describe the Bug

Don't know if this is a missing feature or if the matches () function is broken, but I cannot use it according to the [docs](https://docs.camunda.io/docs/next/components/modeler/feel/builtin-functions/feel-built-in-functions-string/#matchesinput-pattern)

### Steps to Reproduce

https://nikku.github.io/feel-playground/?e=matches%28%22foobar%22%2C+%22%5Efo*bar%22%29&c=%7B%0A%0A%7D&t=expression&st=true

### Problem

Failed to evaluate FEEL expression: not implemented: matches

### Expected Behavior

feel playground supports the matches function

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by falko** [comment]
My current prospect will likely need it.

**Comment by nikku** [comment]
Contributions welcome to implement this.

**Comment by nikku** [comment]
Closing this issue as [upstream tracking issue exists](https://github.com/nikku/feelin/issues/22).
