### ISSUE TITLE
Evaluation error: `not implemented: number`

### ISSUE THREAD

**Issue by ingorichtsmeier** [nikku/feel-playground#4]
__Is your feature request related to a problem? Please describe__

Evaluating the following expression leads to `not implemented: number` error on the playground:

```
number(substring after(
  substring before(
    string(
      years and months duration(
        date(birthday), 
        today()
      )
    ),
    "Y"
  ),
  "P")
)
```

__Describe the solution you'd like__

The result of the expression should be 53. The number conversion function is available: https://docs.camunda.io/docs/components/modeler/feel/builtin-functions/feel-built-in-functions-conversion/#number

__Describe alternatives you've considered__

None.

__Additional context__

Depends on https://github.com/nikku/feelin/issues/19

**Comment by nikku** [comment]
`number` built in is not implemented yet: https://github.com/nikku/feelin/issues/19.

**Comment by nikku** [comment]
Supported nowadas.
