### ISSUE TITLE
FEEL function `matches` is not supported

### ISSUE THREAD

**Issue by Bab64** [nikku/feel-playground#5]
### Describe the Problem

Tested within [DMN FEEL playground](https://nikku.github.io/feel-playground/?e=matches%28%3F%2C%22%5EN*%22%29&c=%7B%0A++%22%3F%22+%3A+%22Nikku%22%0A%7D&t=unaryTest).

```
matches( input, pattern, flags?)
```

Does not seem to be implemented.

**Comment by Bab64** [comment]
Input: **{"?" : "Nikku"}**
Unary test : **matches(?,"^N*")**
https://nikku.github.io/feel-playground/?e=matches%28%3F%2C%22%5EN*%22%29&c=%7B%0A++%22%3F%22+%3A+%22Nikku%22%0A%7D&t=unaryTest

**Comment by nikku** [comment]
Needs fix via https://github.com/nikku/feelin/issues/22.

**Comment by Bab64** [comment]
Thanks
