### ISSUE TITLE
Test function invocation within FEEL Playground

### ISSUE THREAD

**Issue by Bab64** [nikku/feel-playground#8]
The expression `every rate in rates() satisfies rate < 10` is valid within FEEL Playground, but **is it possible** to test it (execute) againt this: `{rates() {return [ 10, 20 ];}}`?
The **Input** area within FEEL Playground expects common JSON... Maybe there is a way of typing something to execute the expression against specific data... or not?
Thanks in advance.

**Comment by nikku** [comment]
This issue probably belongs to the [feel playground repository](https://github.com/nikku/feel-playground)? I've moved it there.

The playground does not allow you to provide functions as input, but you [can test them by defining them as part of the expression](https://nikku.github.io/feel-playground/?e=%7E3YCAkIDhgICAgICAgIC9AgCX7JaWhbH%2BfLiqAwJGq8kixXoeSV%2FB0DmL1svCwimZB3aPV6KPa2Ua4s3%2FvxGUB96ZoHqWAywEFUoHRIm8v9PXOLT4839%2FavcAgA%3D%3D&c=%7B%7D&t=expression&st=true).

If you use feelin, the FEEL interpreter this project builds upon then you can pass [functions via the context](https://github.com/nikku/feelin?tab=readme-ov-file#usage).

**Comment by Bab64** [comment]
Thanks Niko.
